name: flutter_draggable_gridview
description: This package helps you to add drag & drop functionality to exising Gridview.builder.
version: 0.0.1
homepage: https://github.com/Mindinventory/flutter_draggable_gridview

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true